// Generated by scripts/scanner_identity.py; do not edit.
export const SCANNER_IDENTITY = {'engineVersion': 'sha256:73664e091543d9c21f04b7fa8d34c0d9383afba277ab2dcd6ac242fb72426dfe', 'conditionContractHash': 'fc370995768beaa7520e85845662e4bc4caf1c3e9023730b29971e95c141c75e'} as const;
export function assertScannerIdentity(value: unknown): void {
  const identity = value as Partial<typeof SCANNER_IDENTITY> | null;
  if (identity?.engineVersion !== SCANNER_IDENTITY.engineVersion
      || identity?.conditionContractHash !== SCANNER_IDENTITY.conditionContractHash)
    throw new Error('Scanner engine or condition contract is incompatible. Refresh after the matching release is deployed.');
}
