// Generated by scripts/scanner_identity.py; do not edit.
export const SCANNER_IDENTITY = {'engineVersion': 'sha256:a66d9c910e2f67533d27786d868eed8e685ff0ca9dea518561f5b9c4d5e7189d', 'conditionContractHash': '76d9410d79a2d8ad73f61f71f46ad571845ed580ea6cce7172ec7a586a7d3d8a'} as const;
export function assertScannerIdentity(value: unknown): void {
  const identity = value as Partial<typeof SCANNER_IDENTITY> | null;
  if (identity?.engineVersion !== SCANNER_IDENTITY.engineVersion
      || identity?.conditionContractHash !== SCANNER_IDENTITY.conditionContractHash)
    throw new Error('Scanner engine or condition contract is incompatible. Refresh after the matching release is deployed.');
}
