// Generated by scripts/scanner_identity.py; do not edit.
export const SCANNER_IDENTITY = {'engineVersion': 'sha256:8fe022fbd07a5bf5685bab5f65791d6eefe06d85449dd8aec0394a1866b1a537', 'conditionContractHash': '0cccfab50fc1698228e474d5df8c96197fa590de8f83ed90b4ccc5fe119e5624'} as const;
export function assertScannerIdentity(value: unknown): void {
  const identity = value as Partial<typeof SCANNER_IDENTITY> | null;
  if (identity?.engineVersion !== SCANNER_IDENTITY.engineVersion
      || identity?.conditionContractHash !== SCANNER_IDENTITY.conditionContractHash)
    throw new Error('Scanner engine or condition contract is incompatible. Refresh after the matching release is deployed.');
}
