"""Generate/check the shared scanner identity after formula or contract edits."""
import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT_FILES = ['frontend/src/data/conditionCatalog.ts', 'frontend/src/types/screener.ts',
                  'frontend/src/data/nativeConditions.json', 'frontend/src/data/baseMetrics.json', 'frontend/src/data/presetDefinitions.json',
                  'DO NOT DELETE EDL PIPELINE/tests/fixtures/reference_screener_contract.json']
ENGINE_FILES = ['frontend/src/engine/baseConditions.ts', 'frontend/src/engine/expression.ts', 'frontend/src/engine/historyEngine.ts',
                'frontend/src/engine/queryCompiler.ts', 'frontend/src/api/snapshotScreen.ts',
                'frontend/src/api/capabilityRegistry.ts', 'frontend/scanner_bridge.py',
                'DO NOT DELETE EDL PIPELINE/screen_trend_conditions.py']
ENGINE_FILES += [path.relative_to(ROOT).as_posix() for path in
                 (ROOT / 'DO NOT DELETE EDL PIPELINE/src/edl_pipeline/scanner').glob('*.py')]


def fingerprint(files):
    digest = hashlib.sha256()
    for name in sorted(files):
        data = (ROOT / name).read_bytes().replace(b'\r\n', b'\n').replace(b'\r', b'\n')
        digest.update(name.encode() + b'\0' + len(data).to_bytes(8, 'big') + data)
    return digest.hexdigest()


def identity():
    return {'engineVersion': 'sha256:' + fingerprint(ENGINE_FILES),
            'conditionContractHash': fingerprint(CONTRACT_FILES)}


def generated_source():
    values = identity()
    return ('// Generated by scripts/scanner_identity.py; do not edit.\n'
            f'export const SCANNER_IDENTITY = {values!r} as const;\n'
            'export function assertScannerIdentity(value: unknown): void {\n'
            '  const identity = value as Partial<typeof SCANNER_IDENTITY> | null;\n'
            '  if (identity?.engineVersion !== SCANNER_IDENTITY.engineVersion\n'
            '      || identity?.conditionContractHash !== SCANNER_IDENTITY.conditionContractHash)\n'
            "    throw new Error('Scanner engine or condition contract is incompatible. Refresh after the matching release is deployed.');\n"
            '}\n')


def checked_identity():
    if (ROOT / 'frontend/src/engine/compatibility.ts').read_text() != generated_source():
        raise RuntimeError('Scanner identity is stale. Run python3 scripts/scanner_identity.py before publication.')
    return identity()


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.check:
        checked_identity()
    else:
        (ROOT / 'frontend/src/engine/compatibility.ts').write_text(generated_source())
